name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: seohyun-kim/conferences-web:latest

      - name: Deploy to server
        run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} compu@bmw.selen.monster "docker pull seohyun-kim/conferences-web:latest && docker run -d seohyun-kim/conferences-web:latest"


